class_name CargoMidData
extends RefCounted
## Generated by art/cargo_mid.py with assets/models/cargo_mid.glb: don't edit by hand.

## Glyph advances (cap height 1) for the gl_<c> parts.
const ADVANCE := {"A": 0.9667, "B": 0.8159, "C": 1.0261, "D": 1.0870, "E": 0.7246, "F": 0.6797, "G": 1.0725, "H": 1.0565, "I": 0.3623, "J": 0.3623, "K": 0.9507, "L": 0.7101, "M": 1.1319, "N": 1.1319, "O": 1.1928, "P": 0.7391, "Q": 1.1928, "R": 0.8754, "S": 0.6638, "T": 0.8754, "U": 1.0261, "V": 0.8754, "W": 1.5101, "X": 1.0261, "Y": 0.8754, "Z": 0.9362, " ": 0.4029}
## [point, outward normal] down the port (+X) bow at the name's height, NAME_Y, every
## 0.4 m from z = 8.0 (starboard: mirror x).
const NAME_Y := 2.35
const BOW := [
	[Vector3(5.600, 2.350, 8.000), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 8.400), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 8.800), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 9.200), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 9.600), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 10.000), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 10.400), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 10.800), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 11.200), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 11.600), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 12.000), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 12.400), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 12.800), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 13.200), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 13.600), Vector3(1.0000, -0.0000, -0.0000)],
	[Vector3(5.600, 2.350, 14.000), Vector3(1.0000, -0.0000, 0.0000)],
	[Vector3(5.600, 2.350, 14.400), Vector3(1.0000, -0.0002, 0.0023)],
	[Vector3(5.598, 2.350, 14.800), Vector3(1.0000, -0.0010, 0.0061)],
	[Vector3(5.595, 2.350, 15.200), Vector3(0.9999, -0.0024, 0.0108)],
	[Vector3(5.589, 2.350, 15.600), Vector3(0.9999, -0.0044, 0.0162)],
	[Vector3(5.582, 2.350, 16.000), Vector3(0.9997, -0.0070, 0.0222)],
	[Vector3(5.571, 2.350, 16.400), Vector3(0.9995, -0.0101, 0.0288)],
	[Vector3(5.558, 2.350, 16.800), Vector3(0.9993, -0.0137, 0.0360)],
	[Vector3(5.543, 2.350, 17.200), Vector3(0.9989, -0.0179, 0.0436)],
	[Vector3(5.524, 2.350, 17.600), Vector3(0.9984, -0.0225, 0.0517)],
	[Vector3(5.501, 2.350, 18.000), Vector3(0.9978, -0.0276, 0.0602)],
	[Vector3(5.475, 2.350, 18.400), Vector3(0.9971, -0.0330, 0.0692)],
	[Vector3(5.446, 2.350, 18.800), Vector3(0.9961, -0.0389, 0.0786)],
	[Vector3(5.412, 2.350, 19.200), Vector3(0.9951, -0.0452, 0.0885)],
	[Vector3(5.374, 2.350, 19.600), Vector3(0.9938, -0.0518, 0.0988)],
	[Vector3(5.332, 2.350, 20.000), Vector3(0.9922, -0.0587, 0.1096)],
	[Vector3(5.286, 2.350, 20.400), Vector3(0.9905, -0.0660, 0.1209)],
	[Vector3(5.235, 2.350, 20.800), Vector3(0.9884, -0.0735, 0.1327)],
	[Vector3(5.178, 2.350, 21.200), Vector3(0.9861, -0.0813, 0.1449)],
	[Vector3(5.117, 2.350, 21.600), Vector3(0.9834, -0.0894, 0.1577)],
	[Vector3(5.050, 2.350, 22.000), Vector3(0.9804, -0.0977, 0.1711)],
	[Vector3(4.977, 2.350, 22.400), Vector3(0.9770, -0.1063, 0.1850)],
	[Vector3(4.898, 2.350, 22.800), Vector3(0.9731, -0.1150, 0.1996)],
	[Vector3(4.813, 2.350, 23.200), Vector3(0.9687, -0.1240, 0.2149)],
	[Vector3(4.721, 2.350, 23.600), Vector3(0.9638, -0.1332, 0.2310)],
	[Vector3(4.621, 2.350, 24.000), Vector3(0.9583, -0.1426, 0.2478)],
	[Vector3(4.514, 2.350, 24.400), Vector3(0.9520, -0.1522, 0.2656)],
	[Vector3(4.398, 2.350, 24.800), Vector3(0.9450, -0.1620, 0.2843)],
	[Vector3(4.273, 2.350, 25.200), Vector3(0.9370, -0.1720, 0.3042)],
	[Vector3(4.138, 2.350, 25.600), Vector3(0.9279, -0.1823, 0.3253)],
	[Vector3(3.992, 2.350, 26.000), Vector3(0.9175, -0.1929, 0.3479)],
	[Vector3(3.834, 2.350, 26.400), Vector3(0.9056, -0.2038, 0.3721)],
	[Vector3(3.663, 2.350, 26.800), Vector3(0.8917, -0.2151, 0.3983)],
	[Vector3(3.476, 2.350, 27.200), Vector3(0.8754, -0.2269, 0.4268)],
	[Vector3(3.272, 2.350, 27.600), Vector3(0.8561, -0.2394, 0.4581)],
]
## The transom's plane and its half breadth at the deck.
const TRANSOM_Z := -32.0
const TRANSOM_HW := 5.100
## Container slots: hatch middles (each a 40 ft bay, or two 20 ft ones BAY_PITCH apart),
## the rows' x, and the covers' top the bottom tier stands on.
const HATCH_Z := [-13.26, 0.0, 13.26]
const BAY_PITCH := 6.26
const COL_X := [-3.69, -1.23, 1.23, 3.69]
const COVER_TOP := 4.3
const CONTAINER_H := 2.59
const LINES := ["kestrel", "brant", "tideway", "norvik", "halcyon", "alder", "skua", "zephyr", "grey", "beige", "rust"]
const REEFERS := ["norvik", "kestrel", "alder"]
## Lights, in the ship's frame.
const FORE_MAST := Vector3(0, 11, 29)
const AFT_MAST := Vector3(0, 19.4, -22.2)
const SIDELIGHT := Vector3(6.38, 14.25, -20.55)
const STERN_LIGHT := Vector3(0, 4.55, -32.12)
const BRIDGE_Z := Vector2(-23.6, -20.0)
const BRIDGE_HW := 4.3
const BRIDGE_SILL := 14.25
