class_name VehicleData
extends RefCounted
## Generated by art/vehicles.py with assets/models/vehicles.glb: don't edit by hand.

## Per variant (glb part prefix): size (width, height, length, m) and the centres of
## the right-hand head and tail lamps (+Z front; mirror x for the left).
const VARIANTS := {
	"sedan_modern": {"size": Vector3(1.840, 1.450, 4.850), "head": Vector3(0.570, 0.665, 2.425), "tail": Vector3(0.595, 0.855, -2.425)},
	"sedan_sport": {"size": Vector3(1.800, 1.440, 4.600), "head": Vector3(0.600, 0.655, 2.300), "tail": Vector3(0.615, 0.855, -2.300)},
	"sedan_boxy": {"size": Vector3(1.700, 1.380, 4.620), "head": Vector3(0.580, 0.660, 2.310), "tail": Vector3(0.590, 0.750, -2.310)},
	"sedan_nineties": {"size": Vector3(1.780, 1.410, 4.800), "head": Vector3(0.560, 0.650, 2.400), "tail": Vector3(0.580, 0.835, -2.400)},
	"sedan_luxury": {"size": Vector3(1.950, 1.460, 5.350), "head": Vector3(0.650, 0.700, 2.675), "tail": Vector3(0.700, 0.780, -2.675)},
	"sedan_ev": {"size": Vector3(1.860, 1.420, 4.720), "head": Vector3(0.610, 0.570, 2.360), "tail": Vector3(0.700, 0.905, -2.360)},
	"sedan_compact": {"size": Vector3(1.720, 1.480, 4.420), "head": Vector3(0.540, 0.645, 2.210), "tail": Vector3(0.555, 0.875, -2.210)},
	"sedan_exec": {"size": Vector3(1.740, 1.420, 4.750), "head": Vector3(0.530, 0.680, 2.375), "tail": Vector3(0.590, 0.760, -2.375)},
}
