class_name VehicleData
extends RefCounted
## Generated by art/vehicles.py with assets/models/vehicles.glb: don't edit by hand.

## Per variant (glb part prefix): size (width, height, length, m) and the centres of
## the right-hand head and tail lamps (+Z front; mirror x for the left).
const VARIANTS := {
	"sedan_modern": {"size": Vector3(1.840, 1.490, 4.850), "head": Vector3(0.570, 0.665, 2.425), "tail": Vector3(0.595, 0.855, -2.425)},
	"sedan_sport": {"size": Vector3(1.800, 1.480, 4.600), "head": Vector3(0.600, 0.655, 2.300), "tail": Vector3(0.615, 0.855, -2.300)},
	"sedan_boxy": {"size": Vector3(1.700, 1.400, 4.620), "head": Vector3(0.580, 0.660, 2.310), "tail": Vector3(0.590, 0.750, -2.310)},
	"sedan_nineties": {"size": Vector3(1.780, 1.450, 4.800), "head": Vector3(0.560, 0.650, 2.400), "tail": Vector3(0.580, 0.835, -2.400)},
	"sedan_luxury": {"size": Vector3(1.950, 1.490, 5.350), "head": Vector3(0.650, 0.700, 2.675), "tail": Vector3(0.700, 0.780, -2.675)},
	"sedan_ev": {"size": Vector3(1.860, 1.470, 4.720), "head": Vector3(0.610, 0.570, 2.360), "tail": Vector3(0.700, 0.905, -2.360)},
	"sedan_compact": {"size": Vector3(1.720, 1.520, 4.420), "head": Vector3(0.540, 0.645, 2.210), "tail": Vector3(0.555, 0.875, -2.210)},
	"sedan_exec": {"size": Vector3(1.740, 1.450, 4.750), "head": Vector3(0.530, 0.680, 2.375), "tail": Vector3(0.590, 0.760, -2.375)},
	"suv_crossover": {"size": Vector3(1.860, 1.801, 4.600), "head": Vector3(0.600, 0.865, 2.300), "tail": Vector3(0.660, 0.995, -2.300)},
	"suv_threerow": {"size": Vector3(1.930, 1.851, 4.950), "head": Vector3(0.690, 0.885, 2.475), "tail": Vector3(0.652, 1.020, -2.475)},
	"suv_luxury": {"size": Vector3(2.060, 2.040, 5.400), "head": Vector3(0.730, 1.075, 2.700), "tail": Vector3(0.780, 1.055, -2.700)},
	"suv_coupe": {"size": Vector3(2.000, 1.690, 5.100), "head": Vector3(0.690, 0.900, 2.550), "tail": Vector3(0.790, 1.065, -2.550)},
	"suv_ev": {"size": Vector3(1.980, 1.800, 4.950), "head": Vector3(0.750, 0.935, 2.475), "tail": Vector3(0.820, 1.120, -2.475)},
	"suv_cherokee": {"size": Vector3(1.760, 1.776, 4.250), "head": Vector3(0.640, 0.860, 2.125), "tail": Vector3(0.760, 0.800, -2.125)},
	"suv_offroad": {"size": Vector3(1.900, 1.998, 4.620), "head": Vector3(0.590, 0.990, 2.310), "tail": Vector3(0.820, 0.870, -2.310)},
	"suv_nineties": {"size": Vector3(1.750, 1.818, 4.600), "head": Vector3(0.630, 0.840, 2.300), "tail": Vector3(0.743, 0.850, -2.300)},
	"minivan_family": {"size": Vector3(1.960, 1.852, 5.100), "head": Vector3(0.630, 0.780, 2.550), "tail": Vector3(0.745, 0.945, -2.550)},
	"minivan_nineties": {"size": Vector3(1.900, 1.755, 4.950), "head": Vector3(0.650, 0.740, 2.475), "tail": Vector3(0.770, 0.820, -2.475)},
	"minivan_modern": {"size": Vector3(1.960, 1.852, 5.100), "head": Vector3(0.630, 0.770, 2.550), "tail": Vector3(0.745, 0.945, -2.550)},
	"minivan_bold": {"size": Vector3(1.990, 1.810, 5.170), "head": Vector3(0.685, 0.800, 2.585), "tail": Vector3(0.752, 0.945, -2.585)},
	"minivan_compact": {"size": Vector3(1.750, 1.700, 4.500), "head": Vector3(0.550, 0.720, 2.250), "tail": Vector3(0.623, 0.865, -2.250)},
	"minivan_ev": {"size": Vector3(1.980, 1.790, 5.150), "head": Vector3(0.740, 0.780, 2.575), "tail": Vector3(0.780, 0.965, -2.575)},
	"minivan_boxy": {"size": Vector3(1.880, 1.820, 4.850), "head": Vector3(0.650, 0.780, 2.425), "tail": Vector3(0.790, 0.820, -2.425)},
	"minivan_suvish": {"size": Vector3(1.990, 1.860, 5.150), "head": Vector3(0.700, 0.850, 2.575), "tail": Vector3(0.752, 0.945, -2.575)},
	"van_cargo": {"size": Vector3(2.050, 2.540, 5.550), "head": Vector3(0.770, 0.950, 2.775), "tail": Vector3(0.902, 0.960, -2.775)},
	"van_passenger": {"size": Vector3(2.010, 2.130, 5.750), "head": Vector3(0.680, 0.915, 2.875), "tail": Vector3(0.882, 0.910, -2.875)},
	"van_hightop": {"size": Vector3(2.020, 2.790, 5.900), "head": Vector3(0.730, 0.940, 2.950), "tail": Vector3(0.895, 0.960, -2.950)},
	"van_retro": {"size": Vector3(2.000, 2.100, 5.400), "head": Vector3(0.650, 0.885, 2.700), "tail": Vector3(0.880, 0.880, -2.700)},
	"van_camper": {"size": Vector3(2.000, 2.552, 5.300), "head": Vector3(0.750, 0.880, 2.650), "tail": Vector3(0.890, 0.960, -2.650)},
	"van_shuttle": {"size": Vector3(2.020, 2.760, 5.900), "head": Vector3(0.730, 0.940, 2.950), "tail": Vector3(0.895, 0.960, -2.950)},
	"van_compact": {"size": Vector3(1.840, 1.900, 4.750), "head": Vector3(0.630, 0.780, 2.375), "tail": Vector3(0.800, 0.800, -2.375)},
	"van_overland": {"size": Vector3(2.050, 2.830, 5.550), "head": Vector3(0.770, 1.030, 2.775), "tail": Vector3(0.902, 1.030, -2.775)},
}
